 development:
   adapter: mysql2
   encoding: utf8
   database: easymoviy_development
   username: root
   password: root
   host: localhost

 test:
   adapter: mysql2
   encoding: utf8
   database: easymoviy_test
   username: root
   password: root
   host: localhost

 production:
   adapter: mysql2
   database: easymoviy_production
   username: prod
   password: prodpwd