 development:
   adapter: mysql2
   encoding: utf8
   database: easymoviy_development
   username: root
   password: root
   host: localhost

 test:
   adapter: mysql2
   encoding: utf8
   database: easymoviy_test
   username: root
   password: root
   host: localhost

 production:
   adapter: mysql2
   database: easy_moviy_production
   username: deploy 
   password: easy_moviy_production_123